# Generated by Django 2.0.3 on 2018-09-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarAPI', '0004_auto_20180906_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='lineos',
            new_name='linenos',
        ),
        migrations.AddField(
            model_name='cars',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
