# Generated by Django 2.0.3 on 2018-09-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarAPI', '0006_auto_20180906_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='owner',
        ),
    ]
